
class SbieIni:
    def __init__(self, installation_dir: str):
        self.installation_dir = str
        self.sbieini_path = str

        ...

    def execute_sbieini(self, command: str) -> bytes: ...
    def query(self, section: str, setting: str, specify: bool, expand: bool, boxes: bool) -> list: ...
    def set(self, section: str, setting: str, value: str): ...
    def append(self, section: str, setting: str, value: str): ...
    def insert(self, section: str, setting: str, value: str): ...
    def delete(self, section: str, setting: str, value: str): ...